alias gxs="git annex sync --content"
alias gxp="git annex push origin master git-annex"
alias gxa="git annex add"
alias gxaf="git annex add --force"
alias gxg="git annex get"
alias gxi="git annex init"
